### ISSUE TITLE
Doesn't install-- Package download fails with 404.

### ISSUE THREAD

**Issue by j3pic** [GeoffreyPlitt/vagrant-audio#5]
The Vagrantfile tried to download from this URL, but it gets a 404 error:

   http://ppa.launchpad.net/ubuntu-audio-dev/alsa-daily/ubuntu/pool/main/o/oem-audio-hda-daily-dkms/oem-audio-hda-daily-dkms_0.201509251532~ubuntu14.04.1_all.deb

**Comment by GeoffreyPlitt** [comment]
Darn. Sorry, I won't have time to fix this. If you find a solution, I'll merge the PR. Will need to experiment manually and see what the latest commands are to install OSS audio libraries.

Since first figuring this stuff out in 2013, the landscape of VMs has shifted and Docker (et al) is much more popular and widely supported now. An alternative to consider.

**Comment by j3pic** [comment]
This link works, but probably only until Monday.

http://ppa.launchpad.net/ubuntu-audio-dev/alsa-daily/ubuntu/pool/main/o/oem-audio-hda-daily-dkms/oem-audio-hda-daily-dkms_0.201710270746~ubuntu14.04.1_all.deb

**Comment by j3pic** [comment]
This package doesn't install `osstest`, so the install procedure is still broken.

**Comment by j3pic** [comment]
It doesn't create `/dev/dsp` either.

**Comment by j3pic** [comment]
Suddenly, the Vagrantfile looks totally different from how it looked last time I ran it, and now it works (although the sound is kind of distorted). Perhaps I accidentally downloaded something else last time.
